### ISSUE TITLE
非常喜欢可惜不会部署，大佬能出个部署教程吗？

### ISSUE THREAD

**Issue by ztkink** [Chadwuo/li-ji-weapp#42]
非常喜欢可惜不会部署，大佬能出个部署教程吗？

**Comment by Chadwuo** [comment]
那个，微信小程序，谈不上部署，我也实在不知道怎么出个教程。您下载个微信开发者工具，简单了解一下小程序开发，即可。

**Comment by Chadwuo** [comment]
> 非常喜欢可惜不会部署，大佬能出个部署教程吗？

那个，微信小程序，谈不上部署，我也实在不知道怎么出个教程。您下载个微信开发者工具，简单了解一下小程序开发，即可。
