### ISSUE TITLE
折腾了好几天终于正常跑起来了，感谢大佬的解答，下面附上我这些天折腾的步骤，供参考。

### ISSUE THREAD

**Issue by ztkink** [Chadwuo/li-ji-weapp#44]
下载代码导入到微信开发者工具，
在miniprogram终端执行 `npm init -y`，使用默认信息初始化
在miniprogram终端执行`npm i @vant/weapp -S –production`
修改根目录下的app.json里/@vant/前面加/miniprogram_npm/，最终都是像这样的格式`"van-row": "/miniprogram_npm/@vant/weapp/row/index",`
app.js里修改
```
import {
    mpserverless
} from './alicloud/index'
```
为
```
import MPServerless from '@alicloud/mpserverless-sdk'
const mpserverless = new MPServerless(wx, {
    appId: 'wx小程序appid',
    spaceId: '阿里云服务空间id',
    clientSecret: '阿里云服务秘钥',
    endpoint: 'https://api.next.bspapp.com',
    timeout: 40 * 1000
});
```
在阿里云的serverless里创建数据表，book、family、friend、giftOUt、giftReceive、user
serverless里记得绑定微信小程序的appid和secret，微信小程序那边记得绑定阿里云的域名。

**Comment by Chadwuo** [comment]
> 下载代码导入到微信开发者工具， 在miniprogram终端执行 `npm init -y`，使用默认信息初始化 在miniprogram终端执行`npm i @vant/weapp -S –production` 修改根目录下的app.json里/@vant/前面加/miniprogram_npm/，最终都是像这样的格式`"van-row": "/miniprogram_npm/@vant/weapp/row/index",` app.js里修改
> 
> ```
> import {
>     mpserverless
> } from './alicloud/index'
> ```
> 
> 为
> 
> ```
> import MPServerless from '@alicloud/mpserverless-sdk'
> const mpserverless = new MPServerless(wx, {
>     appId: 'wx小程序appid',
>     spaceId: '阿里云服务空间id',
>     clientSecret: '阿里云服务秘钥',
>     endpoint: 'https://api.next.bspapp.com',
>     timeout: 40 * 1000
> });
> ```
> 
> 在阿里云的serverless里创建数据表，book、family、friend、giftOUt、giftReceive、user serverless里记得绑定微信小程序的appid和secret，微信小程序那边记得绑定阿里云的域名。

感谢

**Comment by Chadwuo** [comment]
> 下载代码导入到微信开发者工具， 在miniprogram终端执行 `npm init -y`，使用默认信息初始化 在miniprogram终端执行`npm i @vant/weapp -S –production` 修改根目录下的app.json里/@vant/前面加/miniprogram_npm/，最终都是像这样的格式`"van-row": "/miniprogram_npm/@vant/weapp/row/index",` app.js里修改
> 
> ```
> import {
>     mpserverless
> } from './alicloud/index'
> ```
> 
> 为
> 
> ```
> import MPServerless from '@alicloud/mpserverless-sdk'
> const mpserverless = new MPServerless(wx, {
>     appId: 'wx小程序appid',
>     spaceId: '阿里云服务空间id',
>     clientSecret: '阿里云服务秘钥',
>     endpoint: 'https://api.next.bspapp.com',
>     timeout: 40 * 1000
> });
> ```
> 
> 在阿里云的serverless里创建数据表，book、family、friend、giftOUt、giftReceive、user serverless里记得绑定微信小程序的appid和secret，微信小程序那边记得绑定阿里云的域名。

如果您愿意，希望直接修改readme，然后提交pr，再次感谢
