### ISSUE TITLE
能否做个批量导入的功能

### ISSUE THREAD

**Issue by yang96028** [Chadwuo/li-ji-weapp#56]
目前自己有很多来往人情记录，一个个输入有点麻烦

**Comment by Chadwuo** [comment]
> 目前自己有很多来往人情记录，一个个输入有点麻烦

可能不会做【批量导入】这个，因为批量导入，还需要整理现存记录，使其符合导入模板要求。我可以考虑优化录入界面，针对多条记录连续录入场景下，优化使用体验。晚点就加上，等我哦！感谢你的意见！

**Comment by Chadwuo** [comment]
> > 目前自己有很多来往人情记录，一个个输入有点麻烦
> 
> 可能不会做【批量导入】这个，因为批量导入，还需要整理现存记录，使其符合导入模板要求。我可以考虑优化录入界面，针对多条记录连续录入场景下，优化使用体验。晚点就加上，等我哦！感谢你的意见！

已经增加实验性功能：【连续录入】开关。如果你还有更多想法，请告诉我

**Comment by yang96028** [comment]
1，亲友详情界面，收支感觉可以做一个左右分开的显示方式，例如左边全部是支出，右边全部是收入，类似于下图
![image](https://github.com/Chadwuo/li-ji-weapp/assets/54897869/6457df03-5e62-4eb6-8c84-054ec2274a65)

2，我的-亲友关系，这个可能会有点歧义，我开始还以为是梳理亲友关系，目前的功能感觉和小米一样叫称呼计算好一点
3，我还有这样的场景。对方一个家庭，几代人，都有人情往来，希望增加一个把多个人放到一个家庭功能，然后统计和我这个家庭的收支情况，例如我自己的统计的表格，
![image](https://github.com/Chadwuo/li-ji-weapp/assets/54897869/a5bed074-448d-4f86-b29e-3e92337a9ce2)

**Comment by Chadwuo** [comment]
第1点和第2点，采纳，我会尽快完善。

第3点，我再想想

你的想法太棒了

**Comment by yang96028** [comment]
第一点主要左右分开，能更直观一点，具体效果不强求嘛，可以调整下试试效果，我只会python，不会搞这个，不然自己动手试试搞，以前就一直想弄个记人情的软件

**Comment by yang96028** [comment]
同一个礼薄，添加收礼的时候，如果这个来宾已经添加过，再选择或者输入这个来宾的时候，建议把这个来宾对应的金额默认填写到礼金一栏，因为太多了，填写的时候有时候会重复，如果一填名字就显示金额，我就知道已经添加过了

**Comment by Chadwuo** [comment]
> 同一个礼薄，添加收礼的时候，如果这个来宾已经添加过，再选择或者输入这个来宾的时候，建议把这个来宾对应的金额默认填写到礼金一栏，因为太多了，填写的时候有时候会重复，如果一填名字就显示金额，我就知道已经添加过了

好的
