### ISSUE TITLE
如何运行项目

### ISSUE THREAD

**Issue by shPisces** [Chadwuo/li-ji-weapp#61]
你好：

看到你的项目，很感兴趣。想本地跑一下项目，学习一下代码。但是不知道如何在本地配置项目并运行。能麻烦简单说明一下，本地运行的步骤吗？

万分感谢！！！

**Comment by Chadwuo** [comment]
# 安装依赖
pnpm install

# h5端
pnpm dev:h5
# 微信小程序端
pnpm dev:mp-weixin
